FROM debian:jessie-slim
MAINTAINER Jason Kulatunga <jason@thesparktree.com>

WORKDIR /srv/
ADD ./debian.config.sh /srv/config.sh
RUN chmod u+x  /srv/config.sh

RUN apt-get update && apt-get install -y \
    git && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir ~/.ssh && \
    ssh-keyscan github.com >> ~/.ssh/known_hosts