FROM python:2.7.11-alpine
MAINTAINER Jason Kulatunga <jason@thesparktree.com>

WORKDIR /srv/
ADD ./alpine.config.sh /srv/config.sh
RUN chmod u+x  /srv/config.sh

RUN apk --update --no-cache add \
    build-base libc-dev linux-headers \
    openssl-dev libxml2-dev libxslt-dev openssh \
    python python-dev py-pip git && \
    mkdir ~/.ssh && \
    ssh-keyscan github.com >> ~/.ssh/known_hosts
