FROM python:2.7.11-alpine
MAINTAINER Jason Kulatunga <jason@thesparktree.com>

WORKDIR /srv/

RUN apk --update --no-cache add \
    build-base libc-dev linux-headers \
    openssl-dev libxml2-dev libxslt-dev openssh git && \
    python python-dev py-pip && \
    mkdir ~/.ssh && \
    ssh-keyscan github.com >> ~/.ssh/known_hosts && \

CMD ["sh"]